version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: "junwei"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "court-booking-app"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db_backup.sql:/src/scripts/db_backup.sql
    ports:
      - "5432:5432"
  web:
    platform: linux/amd64
    image: junwei99/court-booking-app-services
    depends_on:
      - db
    ports:
      - "8080:8080"
