name: Deploy on Server

on:
  push:
    branches:
      - junwei99-patch-1

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.check_changes.outputs.has_changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all commits

      - name: Check for changes in a directory
        id: check_changes
        run: |
          changes=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- ./backend)
          # if [ -n "$changes" ]; then
            echo "::set-output name=has_changes::true"
            echo "Changes in backend directory detected."
          # else
          #   echo "::set-output name=has_changes::false"
          #   echo "No changes on the backend" 
          # fi

  deploy:
    needs: check_changes
    if: needs.check_changes.outputs.has_changes == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH key to agent
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private.key
          chmod 600 private.key
          eval `ssh-agent -s`
          ssh-add private.key
          ssh-add -L
      - name: Deploy to Server
        env:
          HOST: ${{ vars.HOST }}
          USER: ${{ vars.USER }}
        run: |
          ssh -vvv -o StrictHostKeyChecking=no -A $USER@$HOST "echo 'Successfully connected to the server'" || echo "SSH Exit Code: $?"
