name: Deploy on Server
on:
  push:
    branches:
      - junwei99-patch-1
jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.check_changes.outputs.has_changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Check for changes in directory
        id: check_changes
        run: |
          # Replace './your-directory' with your directory path
          changes=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- ./backend)
          if [ -n "$changes" ]; then
            echo "::set-output name=has_changes::true"
          fi

